added dt vs mom cut and various fixes

diff --git a/farm/clas6/muProcessing/go_SEL b/farm/clas6/muProcessing/go_SEL
--- a/farm/clas6/muProcessing/go_SEL
+++ b/farm/clas6/muProcessing/go_SEL
@@ -58,16 +58,7 @@ ROOT_DIR=$DEST_DIR/root
 LOG_DIR=$DEST_DIR/log
 PAR_FILE="none"
 
-# if 4 arguments, set the last one to PAR_FILE
-if [ $# -eq 4 ]; then
-	PAR_FILE=$4
-	echo " PAR FILE:               "   $PAR_FILE
-	# check that PAR_FILE exist
-	if [ ! -f $PAR_FILE ]; then
-		echo " ERROR: PAR_FILE does not exist: " $PAR_FILE
-		exit 1
-	fi
-fi
+
 
 # if the file COMMAND doesn't exist, exit
 if [ ! -f $COMMAND ]; then
@@ -83,6 +74,16 @@ echo " Input files directory:  "  $ORIG_DIR
 echo " Output files directory: "  $DEST_DIR
 echo " ROOT files directory:   "  $ROOT_DIR
 echo " Command line:           "  $COMMAND
+# if 4 arguments, set the last one to PAR_FILE
+if [ $# -eq 4 ]; then
+	PAR_FILE=$4
+	echo " PAR FILE:               "   $PAR_FILE
+	# check that PAR_FILE exist
+	if [ ! -f $PAR_FILE ]; then
+		echo " ERROR: PAR_FILE does not exist: " $PAR_FILE
+		exit 1
+	fi
+fi
 echo " "
 
 rm -rf DONE_SEL ; touch DONE_SEL
@@ -116,7 +117,7 @@ do
 
 	# if PAR_FILE is different than "none":
 	if [ $PAR_FILE != "none" ]; then
-		echo " > executing $COMMAND on run: "  $ORIG_DIR/$r.mu  " with output: " $DEST_DIR/$r.mu using pars file $PAR_FILE
+		echo " - $r "
 		$COMMAND  $ORIG_DIR/$r.mu -BEAM_E=5.754 -TARGET=proton -OUTPUT=$DEST_DIR/$r.mu -ROOT_OUTPUT=$ROOT_DIR/$r.root -PARS_FILE=$PAR_FILE > $LOG_DIR/$r.log
 	else
 		echo not set yet
